repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: bedag
    url: https://bedag.github.io/helm-charts/
releases:
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: https://github.com/kubernetes/dashboard/releases/download/kubernetes-dashboard-7.10.1/kubernetes-dashboard-7.10.1.tgz
    createNamespace: true
    values:
      - kong:
          enabled: true
      - auth:
          enabled: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "./fwd.sh"
  - name: dashboard-admin-rbac
    namespace: kubernetes-dashboard
    chart: bedag/raw
    values:
      - dashboard-admin-rbac-values.yaml
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    values:
      - args:
          - --cert-dir=/tmp
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    version: "1.6.2"
    values:
      - ./longhorn-values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "./longhorn-rebuild.sh"
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "longhorn-jobs.yaml", "-n", "longhorn-system"]
