# helmfile.yaml
#
repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: bedag
    url: https://bedag.github.io/helm-charts/ 
  #- name: kubernetes-dashboard
  #  url: https://kubernetes.github.io/dashboard/
releases:
  # ── Kubernetes Dashboard and Metrics Server ─────────────────────────────────
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: https://github.com/kubernetes/dashboard/releases/download/kubernetes-dashboard-7.10.1/kubernetes-dashboard-7.10.1.tgz
    createNamespace: true
    atomic: true
    timeout: 600
    values:
      - ./kubernetes-dashboard-values.yaml
  - name: dashboard-admin-rbac
    namespace: kubernetes-dashboard
    chart: bedag/raw 
    version: 2.0.0
    values:
      - ./dashboard-admin-rbac-values.yaml
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    values:
      - args:
          - --kubelet-insecure-tls
  # ── Longhorn ──────────────────────────────────────────────────────────────
  - name: longhorn
    namespace: longhorn-system
    createNamespace: true
    chart: longhorn/longhorn
    version: "1.6.2"
    values:
      - ./longhorn-values.yaml
    # Use a hook to apply your extra config after longhorn is ready
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "./longhorn-rebuild.sh"
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "longhorn-jobs.yaml", "-n", "longhorn-system"]
hooks:
  - events: ["cleanup"]
    showlogs: true
    command: ./fwd.sh
