apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.instanceName }}-ingress
  namespace: {{ .Values.instanceName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.instanceName }}-service
            port:
              number: {{ .Values.gateway.port }}
