apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instanceName }}-service
  namespace: {{ .Values.instanceName }}
  labels:
    app: {{ .Values.instanceName }}
spec:
  selector:
    app: {{ .Values.instanceName }}
  ports:
  - name: gateway
    port: {{ .Values.gateway.port }}
    targetPort: {{ .Values.gateway.port }}
  type: ClusterIP
