#!/usr/bin/env bash
# =============================================================
# helper.sh — Auto-generated by Terraform. DO NOT EDIT MANUALLY.
# Generated: ${generated_at}
# =============================================================
set -euo pipefail
OUT_DIR="${out_dir}"
SCRIPTS_DIR="${scripts_dir}"
MASTER_NAME="${master_name}"
WORKER1_NAME="${worker1_name}"
WORKER2_NAME="${worker2_name}"
MASTER_MEMORY="${master_memory}"
MASTER_CPUS="${master_cpus}"
WORKER_MEMORY="${worker_memory}"
WORKER_CPUS="${worker_cpus}"
DISK_SIZE="${disk_size}"
# ------- Functions -------
usage() {
  echo "Usage: $0 <command>"
  echo ""
  echo "Commands:"
  echo "  create-master       Create the k8s master VM"
  echo "  create-worker1      Create k8s worker 1"
  echo "  create-worker2      Create k8s worker 2"
  echo "  create-all          Create all VMs in order"
  echo "  show-ips            Print IPs from output files"
  echo "  help                Show this message"
}
create_master() {
  echo "[helper] Creating master: $MASTER_NAME"
  "$SCRIPTS_DIR/create-vm.sh" master "$MASTER_NAME" \
    "$MASTER_MEMORY" "$MASTER_CPUS" "$DISK_SIZE" \
    "$OUT_DIR/master-ip.txt"
}
create_worker1() {
  echo "[helper] Creating worker1: $WORKER1_NAME"
  "$SCRIPTS_DIR/create-vm.sh" worker "$WORKER1_NAME" \
    "$WORKER_MEMORY" "$WORKER_CPUS" "$DISK_SIZE" \
    "$OUT_DIR/worker1-ip.txt"
}
create_worker2() {
  echo "[helper] Creating worker2: $WORKER2_NAME"
  "$SCRIPTS_DIR/create-vm.sh" worker "$WORKER2_NAME" \
    "$WORKER_MEMORY" "$WORKER_CPUS" "$DISK_SIZE" \
    "$OUT_DIR/worker2-ip.txt"
}
create_all() {
  echo "[helper] Creating all VMs in order..."
  create_master
  create_worker1
  create_worker2
  echo "[helper] All VMs created."
}
show_ips() {
  for f in "$OUT_DIR"/master-ip.txt "$OUT_DIR"/worker1-ip.txt "$OUT_DIR"/worker2-ip.txt; do
    if [[ -f "$f" ]]; then
      echo "$(basename $f .txt): $(cat $f)"
    else
      echo "$(basename $f .txt): NOT FOUND"
    fi
  done
}
# ------- Dispatch -------
case "$${1:-help}" in   # $${} escapes the $ so Terraform doesn't interpret it
  create-master)  create_master  ;;
  create-worker1) create_worker1 ;;
  create-worker2) create_worker2 ;;
  create-all)     create_all     ;;
  show-ips)       show_ips       ;;
  help|*)         usage          ;;
esac
