defaultSettings:
  replicaSoftAntiAffinity: true
  storageOverProvisioningPercentage: 500
  storageMinimalAvailablePercentage: 10
  defaultReplicaCount: 2
  backupTarget: "cifs://192.168.50.188/longhorn-backups"
  backupTargetCredentialSecret: "cifs-secret"
persistence:
  defaultClassReplicaCount: 2
